apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: batistondeoliveira/gitopsfc
  newTag: df6307f5e579c43e0b053d618b4207a5facc27a5
